[package]
name = "poni-cc"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
paste = "1.0.15"
poni-arena = { git = "https://github.com/HoneyPony/poniescript", branch = "misc", version = "0.1.0" }
rustc-hash = "2.1.1"
